apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  containers:
    - name: redis
      image: redislabs/redismod
      ports:
        - containerPort: 6379
      imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    name: redis
  ports:
    - port: 6379
      targetPort: 6379